version: '3'

services:

  redis:
    image: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 127.0.0.1:9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 127.0.0.1:5601:5601
    depends_on:
      - elasticsearch

  mongo:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017

  tor:
    image: zeta0/alpine-tor
    environment:
      - tors=40

  spider:
    image: tor-spider
    depends_on:
      - tor
      - redis
      - elasticsearch
      - mongo
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - REDIS_URI=${REDIS_URI}
      - ELASTIC_URI=${ELASTIC_URI}
      - ELASTIC_INDEX=${ELASTIC_INDEX}
      - PROXY_URI=${PROXY_URI}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COL=${MONGO_COL}
      - BLACKLIST_FILE=${BLACKLIST_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
      - WORKERS=${WORKERS}
      - PARALLELISM=${PARALLELISM}
      - DEPTH=${DEPTH}
      - LOG_STATUS_INTERVAL=${LOG_STATUS_INTERVAL}
