version: '3'

services:

  redis:
    image: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 127.0.0.1:9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 127.0.0.1:5601:5601
    depends_on:
      - elasticsearch

  mongo:
    image: mongo

  tor:
    image: multitor
    command: bash -c "multitor --init 20 --user root --socks-port 9000 --control-port 9900 --proxy privoxy --haproxy --verbose --debug > /tmp/multitor.log && tail -f /tmp/multitor.log"

  spider:
    image: tor-spider
    depends_on:
      - tor
      - redis
      - elasticsearch
      - mongo
    ports:
      - 127.0.0.1:8888:8888
    environment:
      - REDIS_URI=${REDIS_URI}
      - ELASTIC_URI=${ELASTIC_URI}
      - ELASTIC_INDEX=${ELASTIC_INDEX}
      - PROXY_URI=${PROXY_URI}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - MONGO_COL=${MONGO_COL}
